//v185 Copyright (c) 2008-2023 33Across Inc. All Rights Reserved

Tynt=window.Tynt||[];
"undefined"==typeof Tynt.TIL&&"undefined"==typeof Tynt.TCL&&"undefined"==typeof Tynt.TICFL&&function(){var d=window,h=document,m={distro:"TC",id:"TC-"+(new Date).getTime()};Tynt.TCL=function(){function Y(a,b,c){f.on(a,b,c)}function L(a){var b=L.options;a=b.parser[b.strictMode?"strict":"loose"].exec(a);for(var c={},e=14;e--;)c[b.key[e]]=a[e]||"";c[b.q.name]={};c[b.key[12]].replace(b.q.parser,function(a,e,d){e&&(c[b.q.name][e]=d)});return c}if(document.body){Date.now||(Date.now=function(){return(new Date).getTime()});
var f={_maxRef:600,_idMacro:"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",init:function(){this._icUrl=m.protocol+(Tynt.e||"")+"ic.tynt.com";this._debUrl=m.protocol+(Tynt.e||"")+"de.tynt.com/deb/v2";this._sicUrl=m.protocol+(Tynt.e||"")+"cdn-sic.33across.com/1/javascripts/sic.js";this._apUrl=m.protocol+(Tynt.e||"")+"cdn-ap.33across.com/javascripts/ap.js";this._chmob=this._chua=this._chuav=this._chm=this._chpv=this._chp="";this.init.fbl=function(a,c){if(c)for(var e=0;e<c.length;++e)0<e&&(f[a]+=
", "),f[a]+=c[e].brand+";v="+c[e].version};var a=navigator.userAgentData;"undefined"!=typeof a&&("undefined"!=typeof a.getHighEntropyValues&&(this._chpv="pending",a.getHighEntropyValues(["model","platformVersion","fullVersionList"]).then(function(a){f._chm=a.model;f._chpv=a.platformVersion;f.init.fbl("_chuav",a.fullVersionList)})),this._chp=a.platform,this._chmob=a.mobile,this.init.fbl("_chua",a.brands))},newEle:function(a,b,c,e){e=e||window;a=e.document.createElement(a);b&&this.extend(a,b);c&&this.extend(a.style,
c);return a},injectScript:function(a,b,c){b=b||window;a=this.newEle("script",{async:"async",referrerPolicy:"unsafe-url",type:"text/javascript",src:a},null,b);this.insertEle(a,c||b.document.getElementsByTagName("script")[0])},injectSicScript:function(a){this.injectScript(this._sicUrl,window,a)},injectApolloScript:function(){this.injectScript(this._apUrl)},injectSicIframe:function(a,b,c){var e={width:a.width+"px",height:a.height+"px",border:"0 none",margin:"0"};c&&this.extend(e,c);c=this.newEle("iframe",
{referrerPolicy:"unsafe-url",src:"about:blank",frameBorder:"0",frameSpacing:"0",scrolling:"no"},e);this.insertEle(c,b);a.iframeId=this.eleId(c);a.sicWindow=c.contentWindow;a=c.contentWindow.document;a.open();a.write('<!DOCTYPE html><html><head><style type="text/css">*{margin:0;padding:0;}</style></head><body><script type="text/javascript">window.Tynt = window.parent.Tynt;\x3c/script><script type="text/javascript" src="'+this._sicUrl+'">\x3c/script></body></html>');a.close()},insertEle:function(a,
b){b?"script"==b.tagName.toLowerCase()?b.parentNode.insertBefore(a,b):b.appendChild(a):document.body.appendChild(a)},eleId:function(a){var b=a.id;b||(b="x33x"+Date.now(),a.id=b);return b},_imgs:[],injectPixel:function(a,b,c){var e;try{e=h.createElement("img")}catch(d){e=document.createElement("img")}e&&(this._imgs.push(e),b&&(e.onload=b),c&&(e.onerror=c),e.referrerPolicy="unsafe-url",e.src=a)},docUrl:function(){var a=this.getLink("canonical");a||(a=this.getMeta("property","og:url","name","original-source"));
if(a){if(0!=a.indexOf("http")){var b=m.protocol+d.location.host+d.location.pathname,c=h.getElementsByTagName("base")[0];c&&(c=c.getAttribute("href"))&&(b=c);"/"==a.charAt(0)?(c=b.indexOf("/",9),-1<c&&(b=b.slice(0,c))):(c=b.lastIndexOf("/"),b=9<c?b.slice(0,c+1):b+"/");a=b+a}return a}return""},getMeta:function(a,b,c,e){var d,f=null,t=null,r=h.getElementsByTagName("meta");for(d=0;d<r.length;++d)f||r[d].getAttribute(a)!==b?c&&!t&&r[d].getAttribute(c)===e&&(t=r[d].getAttribute("content")||null):f=r[d].getAttribute("content")||
null;return f||t},getLink:function(a,b){var c,e,d=h.getElementsByTagName("link");for(c=0;c<d.length;++c)if(e=d[c].getAttribute("rel"),d[c].getAttribute("href")&&e&&(!b&&0<=e.indexOf(a)||b&&e==a))return d[c].href;return null},extend:function(a,b){var c,e;for(c=1;c<arguments.length;++c)for(e in arguments[c])arguments[c].hasOwnProperty(e)&&(a[e]=arguments[c][e]);return a},isArray:function(a){return"undefined"!=typeof a&&"[object Array]"===Object.prototype.toString.call(a)},inArray:function(a,b){return 0<=
this.indexOf(a,b)},toArray:function(a,b){return Array.prototype.slice.call(a,b||0)},indexOf:function(a,b){if(a.indexOf)return a.indexOf(b);for(var c=0;c<a.length;++c)if(a[c]===b)return c;return-1},unique:function(a){var b,c={},e=[];for(b=0;b<a.length;++b)c[a[b]]||(c[a[b]]=!0,e.push(a[b]));return e},iframeType:function(){var a=this.iframeEle(),b=M;if(a)b=a.id&&0<=a.id.search(/google_ads?_i?frame/)?6:N;else try{window!=window.top&&(b="undefined"!=typeof window.$sf?O:H)}catch(c){b=H,f.clog("iframeType: "+
c.message)}return b},iframeEle:function(a){var b=null;a=a||window;try{b=a.frameElement}catch(c){}return b},iframeTop:function(){var a=window,b=null;try{for(;a!=window.top;)b=a,a=a.parent}catch(c){return null}return b?this.iframeEle(b):null},getTopWin:function(){var a=window;try{for(;a.parent!==a&&a.parent.document;)a=a.parent}catch(b){}return a},isolated:function(){var a=!0;try{"function"==typeof window.top.open&&(a=!1)}catch(b){}return a},tyntIds:function(){return this.unique(Tynt).join("~")},getPubId:function(){for(var a=
null,b=0;b<Tynt.length;++b)if("string"==typeof Tynt[b]&&22==Tynt[b].length&&0>Tynt[b].indexOf("!")){a=Tynt[b];break}return a},countIds:function(a){var b,c=0;for(b=0;b<Tynt.length;++b)Tynt[b]===a&&++c;return c},_log:function(a){"undefined"==typeof Tynt.debug&&0<d.location.search.indexOf("__tcdebugmode=1")&&d.console&&d.console.log&&(Tynt.debug=!0);if(!0===Tynt.debug||1===Tynt.debug)a.unshift("[TC]"),d.console.log.apply(d.console,a)},log:function(){m.inXOIframe()?this.clog.apply(this,arguments):this._log(this.toArray(arguments))},
clog:function(){var a=this.toArray(arguments);a.unshift(m.id);this._log(a)},callIcU:function(){d._33Across.state.icDone=P;f.clog("Calling IC/U");this.injectPixel(this._icUrl+"/u",function(){d._33Across.state.icDone=u})},callIcCb:function(){var a,b,c,e,B,A;if(!d._33Across.state.icDone){d._33Across.state.icDone=P;b=this.getCookie(h.cookie,"tracertraffic");a=d.location.hash;a=/tynt=/.test(a)?a.match(/tynt=?([^?&$#]*)/)[1]:!1;var t=this.getPrivacyParameters();e=c=this._icUrl+"/b/p?id="+this.tyntIds()+
(b?"&et="+b:"")+(a?"&a="+a:"")+("string"==typeof Tynt.b?"&b="+Tynt.b:"")+"&lm="+m.type+"&ts="+Date.now()+"&dn="+m.distro+"&iso="+(this.isolated()?"1":"0")+t+"&pu="+encodeURIComponent(this.trunc(this.pageUrl(),f._maxRef));(a=this.getMeta("property","og:title"))&&a!=h.title&&(e+="&ct="+encodeURIComponent(this.trunc(a,200)));B=e;h.referrer&&(a=this.trunc(h.referrer,this._maxRef),B+="&r="+encodeURIComponent(a));A=B;if(a=h.title||d.location.hostname)a=this.trim(this.trunc(a,200)),A+="&t="+encodeURIComponent(a);
b=this.clientHints(A);f.callIcCb.rsp=function(){d._33Across.state.icDone=u};f.clog("Calling IC");this.injectPixel(b,f.callIcCb.rsp,function(){f.injectPixel(A,f.callIcCb.rsp,function(){f.injectPixel(B,f.callIcCb.rsp,function(){f.injectPixel(e,f.callIcCb.rsp,function(){f.injectPixel(c,f.callIcCb.rsp)})})})})}},callIc:function(){this.when(function(){return"pending"!=f._chpv},this.callIcCb,{timeout:300,timeoutCallback:this.callIcCb},this)},callDeb:function(a,b,c){function e(a,b){f.clog("Calling DEB "+
b+(a?"":" on IC timeout"));var c=encodeURIComponent(f.trunc(h.referrer,f._maxRef)),e=this.getPrivacyParameters(),g;g=this.clientHints("");f.injectScript(f._debUrl+"?id="+f.tyntIds()+"&dn="+m.distro+"&cc="+b+g+"&r="+c+e+"&pu="+encodeURIComponent(f.trunc(f.pageUrl(),f._maxRef)),d)}"undefined"==typeof a&&(a=1);d._33Across.state.deDone>=a||(++d._33Across.state.deDone,1!==d._33Across.state.deDone&&!0!==c||this.when(function(){return d._33Across.state.icDone==u},e,{timeout:300,timeoutCallback:e,callbackData:d._33Across.state.deDone},
this),b&&0<b.length&&setTimeout(function(){f.callDeb(a,b,!0)},b.shift()))},callDebX:function(a,b){function c(a,c){f[b?"log":"clog"]("Calling DEBx "+c+(a?"":" on IC timeout"));var A=encodeURIComponent(f.trunc(h.referrer,f._maxRef)),t=this.getPrivacyParameters(),r;r=this.clientHints("");f.injectScript(f._debUrl+"?m=xch&id="+f.tyntIds()+"&dn="+m.distro+"&cc="+c+r+"&r="+A+t+"&pu="+encodeURIComponent(f.trunc(f.pageUrl(),f._maxRef)),d)}a||(a=10);d._33Across.state.dxDone>=a||(++d._33Across.state.dxDone,
this.when(function(){return d._33Across.state.icDone==u},c,{timeout:300,timeoutCallback:c,callbackData:d._33Across.state.dxDone},this))},jsonDecode:function(a){if("function"!=typeof Array.prototype.toJSON)return JSON.stringify(a);var b=Array.prototype.toJSON;delete Array.prototype.toJSON;a=JSON.stringify(a);Array.prototype.toJSON=b;return a},getCookie:function(a,b){for(var c=b+"=",e=a.split(";"),d=0;d<e.length;d++){for(var f=e[d];" "==f.charAt(0);)f=f.substring(1,f.length);if(0==f.indexOf(c))return f.substring(c.length,
f.length)}return null},trim:function(a){return a.replace(/^\s+|\s+$/g,"")},trunc:function(a,b){var c,e;if(!a||a.length<=b)return a;c=a.substring(0,b);for(e=1;3>=e;++e)if("%"==c.charAt(c.length-e))return c.substring(0,c.length-e);return c},when:function(a,b,c,e){var f,g,t,r=null,h=null,C=a();c=c||{};f=c.interval||50;g=c.timeout;t=c.timeoutCallback||function(){};if(C)return b.call(e,C,c.callbackData),!0;r=d.setInterval(function(){if(C=a())d.clearInterval(r),d.clearTimeout(h),b.call(e,C,c.callbackData)},
f);g&&(h=d.setTimeout(function(){d.clearInterval(r);t.call(e,C,c.callbackData)},g));return!1},prob:function(a){a=parseFloat(a)||0;return Math.random()<a},on:function(a,b,c,e){a.addEventListener?a.addEventListener(b,c,e||!1):a.attachEvent&&a.attachEvent("on"+b,c)},off:function(a,b,c,e){a.removeEventListener?a.removeEventListener(b,c,e||!1):a.detachEvent&&a.detachEvent("on"+b,c)},pageUrl:function(){return m.inXOIframe()?h.referrer:d.location.href},clientHints:function(a){"pending"!=this._chpv&&(this._chm&&
(a+="&chm="+encodeURIComponent(this._chm)),this._chpv&&(a+="&chpv="+encodeURIComponent(this._chpv)),this._chuav&&(a+="&chuav="+encodeURIComponent(this._chuav)));this._chp&&(a+="&chp="+encodeURIComponent(this._chp));"boolean"==typeof this._chmob&&(a+="&chmob="+(this._chmob?"1":"0"));this._chua&&(a+="&chua="+encodeURIComponent(this._chua));return a},getPrivacyParameters:function(){return("string"==typeof I.uspString?"&us_privacy="+I.uspString:"")+("string"==typeof g.gppString?"&gpp="+g.gppString:"")+
(Array.isArray(g.gppSid)&&0<g.gppSid.length?"&gpp_sid="+g.gppSid.join(","):"")},getUrlArgs:function(){var a,b,c,e=[];a=location.href.indexOf("?");if(-1!=a)for(b=location.href.substring(a+1,location.href.length).split("&"),a=0;a<b.length;a++)c=b[a].split("="),e[c[0]]=c[1];return e}},I={uspString:null,init:function(){var a=this,b=function(){for(var a=window,b;!b;){try{a.frames.__uspapiLocator&&(b=a)}catch(c){}if(a===window.top)break;a=a.parent}var e={};d.__uspapi=function(a,c,d){if(b){var f="usp-"+
Math.random();a={__uspapiCall:{command:a,callId:f,version:c}};e[f]=d;b.postMessage(a,"*")}else d({msg:"__uspapi not found"},!1)};f.on(window,"message",function(a){var b=a.data;if("string"===typeof a.data)try{b=JSON.parse(a.data)}catch(c){}b.__uspapiReturn&&(a=b.__uspapiReturn,e[a.callId](a.returnValue,a.success),delete e[a.callId])},!1)},c=function(){d.__uspapi("getUSPData",1,function(b,c){c&&(a.uspString=b.uspString)})};d.__uspapi||b();try{c()}catch(e){b(),c()}Tynt.getUspString=function(){return a.uspString};
Tynt.getConsentString=function(){return null}}},g={gppSid:[],gppString:null,gppPromise:null,cmpWindow:null,cmpFound:!1,timeoutMs:1E4,findCmpWindow:function(){for(var a=window,b=null;!b;){try{a.frames.__gppLocator&&(b=a)}catch(c){}if(a===window.top)break;a=a.parent}return g.cmpWindow=b},createCmpProxy:function(){var a={};d.__gpp=function(b,c,e,d){if(g.cmpWindow){var f="33x-gpp-"+Math.random();b={__gppCall:{command:b,parameter:e,version:d,callId:f}};"function"==typeof c&&(a[f]=c);g.cmpWindow.postMessage(b,
"*")}else"function"==typeof c&&c("__gppLocator not found",!1)};f.on(window,"message",function(b){var c=b.data;if("string"===typeof b.data)try{c=JSON.parse(b.data)}catch(e){c=null,f.log("JSON.parse exception:",b.data)}c&&c.__gppReturn&&(b=c.__gppReturn,a[b.callId](b.returnValue,b.success),delete a[b.callId])},!1)},isAppSec:function(a){return a&&Array.isArray(a.applicableSection)&&0<a.applicableSection.length&&0!==a.applicableSection[0]},isAppSecs:function(a){return a&&Array.isArray(a.applicableSections)&&
0<a.applicableSections.length&&0!==a.applicableSections[0]},getApplicableSections:function(a){return g.isAppSecs(a)?a.applicableSections:g.isAppSec(a)?a.applicableSection:[]},startListening:function(){f.log("startListening");var a=d.__gpp("addEventListener",g.handleEvent);a&&f.log("startListening, event returned:",a);a&&a.pingData&&"1.1"!=a.pingData.gppVersion&&g.handleEvent(a)},handleEvent:function(a){if(a&&a.pingData){var b=a.pingData;f.log("handleEvent",b.gppVersion,a);"loaded"==b.cmpStatus&&("1.1"==
b.gppVersion?b.gppString&&b.applicableSections&&g.receiveData(b):g.receiveData(d.__gpp("getGPPData")))}else f.log("handleEvent:",a)},nullData:function(){return{gpp:null,gppSid:[],usp:"function"===typeof Tynt.getUspString?Tynt.getUspString():null,coppa:null,gdpr:null}},init:function(){Tynt.getPrivacySignals=function(){null==g.gppPromise&&(g.gppPromise=new Promise(function(a,c){var e=null;g.cmpFound?e=setTimeout(function(){f.log("_gpp timed-out after "+g.timeoutMs/1E3+" seconds.");a(g.nullData())},
g.timeoutMs):a(g.nullData());g.receiveData=function(c){c&&(g.gppString=c?c.gppString:null,g.gppSid=g.getApplicableSections(c),null!=g.gppString&&(clearTimeout(e),a({gpp:"string"===typeof g.gppString?g.gppString:null,gppSid:g.gppSid,usp:"function"===typeof Tynt.getUspString?Tynt.getUspString():null,coppa:null,gdpr:null})))}}));return g.gppPromise};g.cmpFound="function"===typeof d.__gpp;if(!g.cmpFound){var a=d.location.search;"object"===typeof l&&0<a.indexOf("__tcgppver=1.0")?l.init():"object"===typeof k&&
0<a.indexOf("__tcgppver=1.1")&&k.init();g.cmpFound="function"===typeof d.__gpp}Tynt.getPrivacySignals().then(function(a){f.log("getPrivacySignals resolve:",a)},function(a){f.log("getPrivacySignals reject:",a)});"function"===typeof d.__gpp?g.startListening():m.inIframe()&&m.isolated?null==g.findCmpWindow()?f.log("CMP API not found in frame ancestors."):(g.cmpFound=!0,g.createCmpProxy(),g.startListening()):f.log("CMP API not found in _window.")}},l={pingData:{gppVersion:"1.0",cmpStatus:"stub",cmpDisplayStatus:"hidden",
supportedAPIs:["tcfeuv2","tcfcav1","uspv1"],cmpId:0},mockEvent:function(a,b){var c={eventName:a,listenerId:0,data:b,pingData:l.pingData};f.log("mockEvent",a,b,l.pingData);for(var e=0;e<d.__gpp.events.length;e++)"function"===typeof d.__gpp.events[e].callback&&(c.listenerId=e,d.__gpp.events[e].callback(c,!0))},init:function(){d.__gpp_addFrame_33=function(a){if(!d.frames[a])if(document.body){var b=document.createElement("iframe");b.style.cssText="display:none";b.name=a;document.body.appendChild(b)}else d.setTimeout(d.__gpp_addFrame_33,
10,a)};d.__gpp_mock_33=function(){var a=arguments;if(!a.length)return null;var b=a[0],c=1<a.length?a[1]:null,a=2<a.length?a[2]:null,e=null;if("ping"===b)e=l.pingData;else if("addEventListener"===b)b=++d.__gpp.lastId,d.__gpp.events.push({id:b,callback:c,parameter:a}),e={eventName:"listenerRegistered",listenerId:b,data:!0,pingData:l.pingData};else if("removeEventListener"===b){c=!1;for(b=0;b<d.__gpp.events.length;b++)if(d.__gpp.events[b].id==a){d.__gpp.events[b].splice(b,1);c=!0;break}e={eventName:"listenerRemoved",
listenerId:a,data:c,pingData:l.pingData}}else"getGPPData"===b?"loaded"==l.pingData.cmpStatus?(c=f.getUrlArgs(),a=c.__tcgppstr?c.__tcgppstr:"DBABzw~1YNY~BVQqAAAAAgA",c=(c.__tcgppsid?c.__tcgppsid:"6,7").split(",").map(function(a){return Number(a)}),e={sectionId:3,gppVersion:1,sectionList:c,applicableSections:c,gppString:a,pingData:l.pingData}):e=null:e=null;return e};d.__gpp_msgHandler_33=function(a){var b,c="string"===typeof a.data;try{b=c?JSON.parse(a.data):a.data}catch(e){b=null}if("object"===typeof b&&
null!==b&&"__gppCall"in b){var f=b.__gppCall;d.__gpp(f.command,function(b,e){var d={__gppReturn:{returnValue:b,success:e,callId:f.callId}};a.source.postMessage(c?JSON.stringify(d):d,"*")},"parameter"in f?f.parameter:null,"version"in f?f.version:1)}};d.__gpp=d.__gpp_mock_33;d.__gpp.queue=[];d.__gpp.events=[];d.__gpp.lastId=0;d.addEventListener("message",d.__gpp_msgHandler_33,!1);d.__gpp_addFrame_33("__gppLocator");setTimeout(function(){l.pingData.cmpStatus="loading";l.mockEvent("cmpStatus","loading");
setTimeout(function(){l.pingData.cmpId=3333;l.pingData.cmpStatus="loaded";l.mockEvent("cmpStatus","loaded")},1E3)},1E3)}},k={pingData:{gppVersion:"1.1",cmpStatus:"stub",cmpDisplayStatus:"hidden",signalStatus:"not ready",supportedAPIs:["2:tcfeuv2","5:tcfcav1","6:uspv1"],cmpId:0,sectionList:[],applicableSections:[-1],gppString:"",parsedSections:{}},mockEvent:function(a,b){var c={eventName:a,listenerId:0,data:b,pingData:k.pingData};f.log("mockEvent",a,b,k.pingData);for(var e=0;e<d.__gpp.events.length;e++)"function"===
typeof d.__gpp.events[e].callback&&(c.listenerId=e,d.__gpp.events[e].callback(c,!0))},init:function(){d.__gpp_addFrame_33=function(a){if(!d.frames[a])if(document.body){var b=document.createElement("iframe");b.style.cssText="display:none";b.name=a;document.body.appendChild(b)}else d.setTimeout(d.__gpp_addFrame_33,10,a)};d.__gpp_mock_33=function(){var a=arguments;if(a.length){var b=a[0],c=1<a.length?a[1]:null,a=2<a.length?a[2]:null;if("ping"===b)"function"===typeof c&&c(k.pingData,!0);else if("addEventListener"===
b)b=++d.__gpp.lastId,d.__gpp.events.push({id:b,callback:c,parameter:a}),"function"===typeof c&&c({eventName:"listenerRegistered",listenerId:b,data:!0,pingData:k.pingData},!0);else if("removeEventListener"===b){for(var b=!1,e=0;e<d.__gpp.events.length;e++)if(d.__gpp.events[e].id==a){d.__gpp.events[e].splice(e,1);b=!0;break}"function"===typeof c&&c(b,!0)}}};d.__gpp_msgHandler_33=function(a){var b,c="string"===typeof a.data;try{b=c?JSON.parse(a.data):a.data}catch(e){b=null}if("object"===typeof b&&null!==
b&&"__gppCall"in b){var f=b.__gppCall;d.__gpp(f.command,function(b,e){var d={__gppReturn:{returnValue:b,success:e,callId:f.callId}};a.source.postMessage(c?JSON.stringify(d):d,"*")},"parameter"in f?f.parameter:null,"version"in f?f.version:"1.1")}};d.__gpp=d.__gpp_mock_33;d.__gpp.queue=[];d.__gpp.events=[];d.__gpp.lastId=0;d.addEventListener("message",d.__gpp_msgHandler_33,!1);d.__gpp_addFrame_33("__gppLocator");setTimeout(function(){k.mockEvent("signalStatus","not ready");setTimeout(function(){k.pingData.cmpStatus=
"loading";k.mockEvent("cmpStatus","loading");setTimeout(function(){var a=f.getUrlArgs(),b=a.__tcgppstr?a.__tcgppstr:"DBABzw~1YNY~BVQqAAAAAgA",a=(a.__tcgppsid?a.__tcgppsid:"6,7").split(",").map(function(a){return Number(a)});k.pingData.sectionList=a;k.pingData.applicableSections=a;k.pingData.gppString=b;k.pingData.cmpId=3333;k.pingData.cmpStatus="loaded";k.mockEvent("cmpStatus","loaded");setTimeout(function(){k.pingData.signalStatus="ready";k.mockEvent("signalStatus","ready")},1E3)},1E3)},1E3)},1E3)}},
P=1,u=2,M=0,H=3,O=4,N=5;m.type=0;m.inIframe=function(){return this.type>M};m.inSOIframe=function(){return this.type>=N&&6>=this.type};m.inXOIframe=function(){return this.type>=H&&this.type<=O};m.init=function(){this.type=f.iframeType();this.inSOIframe()&&(d=f.getTopWin(),h=d.document);d._33Across||(d._33Across={});d._33Across.state||(d._33Across.state={icDone:0,deDone:0,dxDone:0,ivDone:!1});this.protocol="https://";f.init();this.isolated=f.isolated();I.init();g.init();f.clog("xoi="+this.inXOIframe()+
", soi="+this.inSOIframe()+", iso="+this.isolated);d._33Across.pvTs||(d._33Across.pvTs=Date.now())};L.options={strictMode:!1,key:"source protocol authority userInfo user password host port relative path directory file query anchor".split(" "),q:{name:"queryKey",parser:/(?:^|&)([^&=]*)=?([^&]*)/g},parser:{strict:/^(?:([^:\/?#]+):)?(?:\/\/((?:(([^:@]*)(?::([^:@]*))?)?@)?([^:\/?#]*)(?::(\d*))?))?((((?:[^?#\/]*\/)*)([^?#]*))(?:\?([^#]*))?(?:#(.*))?)/,loose:/^(?:(?![^:@]+:[^:@\/]*@)([^:\/?#.]+):)?(?:\/\/)?((?:(([^:@]*)(?::([^:@]*))?)?@)?([^:\/?#]*)(?::(\d*))?)(((\/(?:[^?#](?![^?#\/]*\.[^?#\/.]+(?:[?#]|$)))*\/?)?([^?#\/]*))(?:\?([^#]*))?(?:#(.*))?)/}};
m.init();var n=h.body,p=h.documentElement,Z=d.eval("/*@cc_on!@*/false"),Q=function(a,b){for(var c="",e=0;e<b;e++)c+=a;return c},E=Q("a",50),D=(Tynt.e||"")+"ic.tynt.com",R=D+"/b/s",aa=function(a){"complete"==h.readyState?a():Y(d,"load",function(b){setTimeout(function(){"undefined"!=typeof h.readyState||Z||(h.readyState="complete");a()},10)})},w=function(a,b){var c=[],e=function(a,b){var c=m.protocol+a.replace("id="+E,"id="+f.tyntIds()),c=f.clientHints(c);-1<c.indexOf(D+"/b/p?")&&"string"==typeof Tynt.b&&
(c+="&b="+Tynt.b);var e=new Image(1,1);b&&(e.onerror=b);e.src=c};w=function(a,b){c.push([a,b])};aa(function(){w=e;for(var a=0;a<c.length;a++)w(c[a][0],c[a][1]);c=null});w(a,b)},S=function(a){var b=[],c="",e;for(e in a)a.hasOwnProperty(e)&&(b.push(c,e,"=",a[e]),c="&");return b.join("")},U=function(a){for(var b=0,c=100>a.length?a.length:100,e=0;e<c;e++)b+=a.charCodeAt(e);a=Math.floor(3844*Math.random());c=Math.abs(Date.now()-12281184E5);return T(c,7)+T((b+a)%3844,2)},V=function(a){if(62>a)return"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz".charAt(this);
var b=Math.floor(a/62);a-=62*b;return 62<=b?V(b)+"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz".charAt(a):"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz".charAt(b)+"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz".charAt(a)},T=function(a,b){var c=V(a);return Q("0",b-c.length)+c},ba=f.trim((h.title||d.location.hostname).toString()).replace(new RegExp(d.location.hash,"g"),""),ca=function(){if(-1!==h.cookie.indexOf("tracertraffic=")&&(!h.referrer||-1==
h.referrer.indexOf(d.location.host))){var a=d.location.hostname.split("."),b,c=2;do b="tracertraffic=0;path=/;domain=."+a.slice(a.length-c,a.length).join(".")+";expires=Thu, 01 Jan 1970 00:00:00 GMT",h.cookie=b,c++;while(-1==h.cookie.indexOf("tracertraffic=0")&&c<=a.length);-1==h.cookie.indexOf("tracertraffic=0")&&(h.cookie="tracertraffic=0;path=/;expires=Thu, 01 Jan 1970 00:00:00 GMT")}},v=function(){var a=[];return function(b){for(var c=a.length-1;0<=c;c--)if(a[c]==b)return!1;a.unshift(b);3<a.length&&
a.pop();return!0}},da=v(),ea=v(),fa=function(a){var b,c=function(a){d.removeEventListener("blur",c,!1);J(b);return!0};return function(a){b=a.target||a.srcElement;d.removeEventListener("blur",c,!1);"IMG"==b.nodeName&&"A"!=b.parentNode.nodeName&&(d.addEventListener("blur",c,!1),setTimeout(function(){h.removeEventListener("blur",c,!1)},1E4));return!0}}(),W=function(a){J(a.target||a.srcElement,!0)},x,X=function(a){a=a.target||a.srcElement;x="IMG"==a.nodeName?a:null},K=function(a){var b=function(a){return"number"==
typeof a.pageX?{x:a.pageX-(p.scrollLeft?p.scrollLeft:n.scrollLeft),y:a.pageY-(p.scrollTop?p.scrollTop:n.scrollTop)}:{x:a.clientX,y:a.clientY}},c=function(a){a=b(a);return 0>=a.x||0>=a.y||a.x>=n.clientWidth||a.y>=n.clientHeight},e=function(a){a=b(a);return 0>=a.x||0>=a.y||a.x>=p.clientWidth||a.y>=p.clientHeight},d=function(a){return"#document"==a.target.nodeName},f=function(a){a=b(a);return 4>=a.x||4>=a.y||a.x>=p.clientWidth-4||a.y>=p.clientHeight-4},g=function(a){g=navigator.userAgent.match("MSIE")?
h.compatMode&&-1!=h.compatMode.indexOf("CSS")?e:c:navigator.userAgent.match("Firefox")?d:f;g(a)};return function(a){x&&g(a)&&(J(x),x=null);return!0}}();Tynt.ci=function(){var a;return function(b,c){a=c||a;var e=R+["?ci=",b,"&id=",E,"&g=",a,"&r=",encodeURIComponent(h.referrer),"&ts=",Date.now()].join("");w(e)}}();Tynt.st=function(){var a;return function(b,c,e,f){a=e||a;b=[R,"?",encodeURIComponent(b),"=",encodeURIComponent(c),"&id=",E,"&g=",a,"&r=",encodeURIComponent(h.referrer),"&href=",encodeURIComponent(d.location.href),
"&ts=",Date.now()];c="";if(f){c=[];e="";for(var g in f)f.hasOwnProperty(g)&&(c.push(e,encodeURIComponent(g),"=",encodeURIComponent(f[g])),e="&");c="&"+c.join("")}w(b.join("")+c)}}();Tynt.c?v=function(){}:(Tynt.c=!0,Tynt.m=Tynt.m||[],Tynt.n=Tynt.n||[],v=function(){var a=!0,b,c=function(b,c){var e;e=(e=f.trim(c))?e.split(/\s+/i).length:0;var d={id:E,wc:e,c:c,f:a?1:0,t:ba};f.extend(d,b);a=!1;e=d.trace_type;delete d.trace_type;var g=d.g;delete d.g;for(var h=[],k="id wc f w h t c".split(" "),l=0;l<k.length;l++){var p=
k[l],n=d[p];n&&h.push([p,encodeURIComponent(n).replace(/\'/g,"%27")]);delete d[p]}for(var q in d)d.hasOwnProperty(q)&&(k=d[q])&&h.push([q,encodeURIComponent(k).replace(/\'/g,"%27")]);q=[];var l=2048-((m.protocol+D+"/a/t/x#?").length+(3+g.length)+5),p=h.length,y=n=0,z=0,v,u,x,F,G=0;for(q[G]={g:g,tp:null};n<p&&35>q.length;)v=h[n][0],d=h[n][1],x=v.length+2,u=l-x-y,0<u?(k=d.substring(z,z+u),F=k.slice(-2).indexOf("%"),-1<F&&(k=d.substring(z,z+u-2+F),y+=F+2),y+=k.length+x,z+=k.length,q[G][v]=k):y=l,y>=
l&&(q[++G]={g:g,p:G},y=0),z>=d.length&&(n++,z=0);q[0].tp=q.length;w(D+"/b/t/"+e+"?"+S(q[0]));for(g=1;g<q.length;g++)w(D+"/b/x/"+e+"?"+S(q[g]))};d.addEventListener?(navigator.userAgent.match(/Firefox\/2\b/)||n.addEventListener("copy",W,!1),d.addEventListener("mousedown",X,!1),d.addEventListener("dragleave",K,!1),d.addEventListener("dragexit",K,!1),h.addEventListener("contextmenu",fa,!1)):(n.attachEvent("oncopy",W),h.getElementsByTagName("html")[0].attachEvent("ondragleave",K),n.attachEvent("onmousedown",
X));ca();f.callIc();var e=[15E3,15E3,15E3,15E3];"function"===typeof Tynt.TIL?f.callDeb(3,e,!0):f.callDeb(5,e,!0);return function(a,e){if(!h.getElementById("tyntSh")){var g,k,m;e&&(h.selection&&h.selection.createRange?(k=h.selection.createRange(),m=k.duplicate(),g=k.text):(k=d.getSelection(),m=0<k.rangeCount&&k.getRangeAt(0),g=k.toString()));var l=a.src;if(l&&!g&&ea(l)){k={trace_type:3,g:U(l),w:a.width,h:a.height};for(m=0;m<Tynt.n.length;m++)Tynt.n[m](k,l);c(k,l)}else if(g&&f.trim(g).length&&"TEXTAREA"!=
a.nodeName&&"INPUT"!=a.nodeName){l=da(g);k={trace_type:1};l&&(b=U(g));k.g=b;for(var n=!0,p=0;p<Tynt.m.length;p++)n=n&&Tynt.m[p](k,g,m,l);l&&n&&c(k,g)}}}});if(!/tracer=test|tracer=no_tracing|disableTracer=/.test(d.location.href)&&!/disableTracer=y/.test(h.cookie))var J=v()}else setTimeout(function(){Tynt.TCL()},50)};Tynt.TCL()}();
